name: Fetch Active Stocks
on:
  schedule:
    # 8:30 AM to 4:30 PM IST, Monday-Friday
    - cron: '30-59/10 3 * * 1-5'    # 3:30, 3:40, 3:50 AM UTC (8:30, 8:40, 8:50 AM IST)
    - cron: '*/10 4-10 * * 1-5'     # 4:00 AM to 10:50 AM UTC (9:00 AM to 3:50 PM IST)
    - cron: '0-30/10 11 * * 1-5'    # 11:00, 11:10, 11:20, 11:30 AM UTC (4:00, 4:10, 4:20, 4:30 PM IST)
  workflow_dispatch:        # Allow manual triggers

jobs:
  analyze-and-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15     # Prevent hanging workflows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run fetch script
        run: |
          python active_stocks.py

      - name: Commit and push CSV file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/active_stocks_with_reasons.csv
          git commit -m "Update Active Stocks data with Reasons" || echo "No changes to commit"
          git push
