name: Trend

on:
  # Run every 30 minutes during Indian market hours (9 AM - 5 PM IST)
  schedule:
    - cron: '0,30 3-10 * * 1-5'  # Every 30 minutes, Monday to Friday, 3:00-10:30 AM UTC
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run even outside market hours'
        required: false
        default: 'false'
        type: boolean

env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:
  frequent-prediction:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync
    
    - name: Verify environment variables
      run: |
        if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
          echo "❌ TELEGRAM_BOT_TOKEN is not set"
          exit 1
        fi
        if [ -z "$TELEGRAM_CHAT_ID" ]; then
          echo "❌ TELEGRAM_CHAT_ID is not set"
          exit 1
        fi
        echo "✅ Environment variables are set"
    
    - name: Check market hours
      id: market_check
      run: |
        # Get current time in IST
        current_hour=$(TZ='Asia/Kolkata' date +%H)
        current_minute=$(TZ='Asia/Kolkata' date +%M)
        current_day=$(TZ='Asia/Kolkata' date +%u)  # 1=Monday, 7=Sunday
        
        echo "Current IST time: $current_hour:$current_minute"
        echo "Current day: $current_day (1=Monday, 7=Sunday)"
        
        # Check if it's a weekday (1-5) and market hours (9-17)
        if [ "$current_day" -le 5 ] && [ "$current_hour" -ge 9 ] && [ "$current_hour" -le 15 ]; then
          echo "✅ Within market hours - HIGH FREQUENCY MODE"
          echo "run_prediction=true" >> $GITHUB_OUTPUT
        else
          echo "⏰ Outside market hours"
          echo "run_prediction=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Send start notification
      if: steps.market_check.outputs.run_prediction == 'true' || github.event.inputs.force_run == 'true'
      run: |
        MESSAGE="🚀 High-Frequency Prediction Starting
        
        ⏰ Time: $(TZ='Asia/Kolkata' date)
        📊 Mode: 30-minute intervals
        🔄 Run: ${{ github.run_number }}
        
        Analyzing 1-minute data for next hour trend..."
        
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -d "chat_id=${TELEGRAM_CHAT_ID}" \
          -d "text=${MESSAGE}" \
          -d "parse_mode=HTML" || echo "Failed to send start notification"
    
    - name: Run High-Frequency Prediction
      if: steps.market_check.outputs.run_prediction == 'true' || github.event.inputs.force_run == 'true'
      run: |
        echo "🚀 Starting high-frequency market prediction..."
        echo "⏰ Current IST time: $(TZ='Asia/Kolkata' date)"
        
        # Set timeout for the entire prediction process (8 minutes for faster turnaround)
        timeout 480 uv run python trend.py
        
        if [ $? -eq 0 ]; then
          echo "✅ High-frequency prediction completed successfully"
        elif [ $? -eq 124 ]; then
          echo "⏰ High-frequency prediction timed out after 8 minutes"
          exit 1
        else
          echo "❌ High-frequency prediction failed"
          exit 1
        fi
    
    - name: Skip prediction (outside market hours)
      if: steps.market_check.outputs.run_prediction == 'false' && github.event.inputs.force_run != 'true'
      run: |
        echo "⏰ Skipping high-frequency prediction - outside market hours"
        echo "Current time: $(TZ='Asia/Kolkata' date)"
        echo "High-frequency mode: 9 AM - 3:30 PM IST, Monday to Friday (every 30 minutes)"
    
    
    - name: Notify on failure
      if: failure() && env.TELEGRAM_BOT_TOKEN != ''
      run: |
        # Send failure notification via curl
        MESSAGE="🚨 High-Frequency Predictor Failed
        
        ⏰ Time: $(TZ='Asia/Kolkata' date)
        🔗 Workflow: High-Frequency Market Predictor
        📋 Run: ${{ github.run_number }}
        ⚡ Mode: 30-minute intervals
        
        Check logs for details. Regular hourly predictor should still be running."
        
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -d "chat_id=${TELEGRAM_CHAT_ID}" \
          -d "text=${MESSAGE}" \
          -d "parse_mode=HTML" || echo "Failed to send failure notification"
